# Generated by Django 5.1.15 on 2026-08-29 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStoreSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_url', models.CharField(db_index=True, max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('scopes', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shopify Store Session',
                'verbose_name_plural': 'Shopify Store Sessions',
                'db_table': 'shopify_store_sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
