# Generated by Django 5.1.15 on 2026-08-29 04:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCPClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Claude Desktop, Cursor, Antigravity Agent', max_length=100)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_rpm', models.PositiveIntegerField(default=60, help_text='Requests per minute rate limit')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCP Client',
                'verbose_name_plural': 'MCP Clients',
                'db_table': 'mcp_clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(db_index=True, help_text='e.g. get_products, create_order', max_length=100)),
                ('allowed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='channels.mcpclient')),
            ],
            options={
                'verbose_name': 'Tool Permission',
                'verbose_name_plural': 'Tool Permissions',
                'db_table': 'mcp_tool_permissions',
                'ordering': ['client', 'tool_name'],
                'unique_together': {('client', 'tool_name')},
            },
        ),
    ]
